server.port = 8081
spring.application.name=jk-samadhan-backend

# spring.datasource.url=jdbc:postgresql://localhost:5432/jks_db?currentSchema=jks_3nf
spring.datasource.url=jdbc:postgresql://localhost:5432/jks_db_srujan
spring.datasource.username=postgres
spring.datasource.password=srujan

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
 spring.jpa.properties.hibernate.default_schema=jks_3nf

logging.level.org.springframework.security=DEBUG

# spring.sql.init.schema-locations=classpath:migration/redesigned_schema_3nf.sql
# spring.sql.init.mode=never
