spring.application.name=jk-samadhan-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/jk_samadhan_db
spring.datasource.username=postgres
spring.datasource.password=srujan

spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.security=DEBUG

